name: bugit
title: Bugit
issues:
  - https://github.com/canonical/bugit-v2/issues
source-code: https://github.com/canonical/bugit-v2
type: app
base: core24
grade: stable
summary: Cool new bugit
description: |
  This snap is a fresh new UI for bugit
version: "0.2.3"
confinement: devmode # required for ubuntu core to collect logs
license: GPL-3.0+

# cross build no longer works with core 24
# https://forum.snapcraft.io/t/launchpad-and-core24-platforms/46056
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]

environment:
  # required for proper color display
  COLORTERM: truecolor
  # detects if bugit is run through ssh
  SSH_CONNECTION: $SSH_CONNECTION

  # Optionally specify all the following vars manually in the pipx version
  # The values here are already the default values when unspecified,
  # So if you are just using the prod version you don't need to change them

  # production or qastaging
  APPORT_LAUNCHPAD_INSTANCE: production
  # Change this to 1 to enable debug mode
  DEBUG: "0"
  # only used for launchpad
  BUGIT_APP_NAME: bugit-v2
  # change this to the sandbox url for debug mode
  JIRA_SERVER: https://warthogs.atlassian.net
  # optional, lets apt installed python apps find their libraries
  PYTHONPATH: "$PYTHONPATH:$SNAP/usr/lib/python3/dist-packages"

layout:
  /etc/sos.conf:
    bind-file: $SNAP/etc/sos.conf
  /var/lib/usbutils/usb.ids:
    bind-file: $SNAP/var/lib/usbutils/usb.ids
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

apps:
  bugit-v2:
    command-chain:
      - env_wrapper.sh
    command: bin/python3 $SNAP/src/bugit_v2/app.py
    completer: src/bugit_v2/bugit-completer.sh

  dump-standard-info:
    # redirect stderr to suppress errors
    command: bin/python3 $SNAP/src/bugit_v2/dump_standard_info.py

parts:
  launcher:
    plugin: dump
    source: snap/local/scripts

  dump-files:
    plugin: dump
    source: src
    organize:
      "*": src/

  bugit-v2:
    plugin: uv
    source: .
    build-snaps:
      - astral-uv
    stage-packages:
      - dmidecode # provides 'dmidecode'
      - pciutils # provides 'lspci'
    after:
      - dump-files

  acpidump:
    plugin: nil
    stage-packages:
      - acpica-tools # provides "acpidump"
