name: bugit
type: app
base: core22
grade: devel
summary: Cool new bugit
description: |
  This snap is a fresh new UI for bugit
version: "0.2"
confinement: devmode # required for ubuntu core to collect logs

environment:
  COLORTERM: truecolor # required for proper color display
  SSH_CONNECTION: $SSH_CONNECTION # detects if bugit is run through ssh
  # Specify the following manually if you are using the pipx version
  PROD: "1" # remove this to enable debug mode
  APPORT_LAUNCHPAD_INSTANCE: production # production or qastaging
  BUGIT_APP_NAME: bugit-v2 # only used for launchpad
  # change this to the sandbox url for debug mode
  JIRA_SERVER: https://warthogs.atlassian.net
  PYTHONPATH: "$PYTHONPATH:$SNAP/usr/lib/python3/dist-packages"

apps:
  bugit-v2:
    command: bin/python3 $SNAP/src/bugit_v2/app.py

  oem-getlogs:
    command: usr/bin/oem-getlogs

  sosreport:
    # the patches from the original bugit
    # doesn't seem to be required anymore
    command: usr/bin/sosreport

parts:
  dump-files:
    plugin: dump
    source: src
    organize:
      "*": src/

  bugit-v2:
    plugin: uv
    source: .
    build-snaps:
      - astral-uv
    stage-packages:
      - dmidecode # provides 'dmidecode'
      - pciutils # provides 'lspci'
    after:
      - dump-files

  apport:
    plugin: nil
    stage-packages:
      - apport # provides oem-getlogs, only works on core22

  acpidump:
    plugin: nil
    stage-packages:
      - acpica-tools # provides "acpidump"

  sosreport:
    plugin: nil
    stage-packages:
      - sosreport
