name: bugit
title: Bugit
issues:
  - https://github.com/canonical/bugit-v2/issues
source-code: https://github.com/canonical/bugit-v2
type: app
base: core24
grade: stable
summary: Cool new bugit
description: |
  This snap is a fresh new UI for bugit
version: "0.2.8"
confinement: devmode # required for ubuntu core to collect logs
license: GPL-3.0+

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]

environment:
  # required for proper color display
  COLORTERM: truecolor
  # detects if bugit is run through ssh
  SSH_CONNECTION: $SSH_CONNECTION

  # Optionally specify all the following vars manually in the pipx version
  # The values here are already the default values when unspecified,
  # So if you are just using the prod version you don't need to change them

  # production or qastaging
  APPORT_LAUNCHPAD_INSTANCE: production
  # Change this to 1 to enable debug mode
  DEBUG: "0"
  # only used for launchpad
  BUGIT_APP_NAME: bugit-v2
  # change this to the sandbox url for debug mode
  JIRA_SERVER: https://warthogs.atlassian.net
  # optional, lets apt installed python apps find their libraries
  PYTHONPATH: "$PYTHONPATH:$SNAP/usr/lib/python3/dist-packages"

layout:
  /etc/sos.conf:
    bind-file: $SNAP/etc/sos.conf
  # this combined with the 'cp' in the install hook
  # overrides platform.freedesktop_os_release()
  # also keep it in SNAP_COMMON to prevent it from being deleted during refresh
  /usr/lib/os-release:
    bind-file: $SNAP_COMMON/etc/os-release
  /var/lib/usbutils/usb.ids:
    bind-file: $SNAP/var/lib/usbutils/usb.ids
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

apps:
  bugit-v2:
    command-chain:
      - env_wrapper.sh
    command: bin/python3 $SNAP/src/bugit_v2/app.py
    # completer is broken after 0.2.6
    # completer: src/bugit_v2/bugit-completer.sh

  dump-standard-info:
    # redirect stderr to suppress errors
    command: bin/python3 $SNAP/src/bugit_v2/scripts/dump_standard_info.py

  list-sessions:
    # redirect stderr to suppress errors
    command: bin/python3 $SNAP/src/bugit_v2/scripts/list_sessions.py

  dut-info:
    # redirect stderr to suppress errors
    command: bin/python3 $SNAP/src/bugit_v2/scripts/save_dut_info.py

parts:
  launcher:
    plugin: dump
    source: snap/local/scripts

  dump-files:
    plugin: dump
    source: src
    organize:
      "*": src/

  bugit-v2:
    plugin: uv
    source: .
    build-snaps:
      - astral-uv
    build-packages:
      - libsystemd-dev
    stage-packages:
      - dmidecode # provides 'dmidecode'
      - pciutils # provides 'lspci'
    after:
      - dump-files
    override-build: |
      craftctl default
      $CRAFT_PART_INSTALL/bin/python3 -m compileall -q -j $CRAFT_PARALLEL_BUILD_COUNT $CRAFT_PART_INSTALL/lib

  acpidump:
    plugin: nil
    stage-packages:
      - acpica-tools # provides "acpidump"

  apport:
    plugin: nil
    stage-packages:
      - apport
