name: bugit
title: Bugit
issues:
  - https://github.com/canonical/bugit-v2/issues
source-code: https://github.com/canonical/bugit-v2
type: app
base: core22
grade: stable
summary: Cool new bugit
description: |
  This snap is a fresh new UI for bugit
version: "0.2.2"
confinement: devmode # required for ubuntu core to collect logs
license: GPL-3.0+
assumes:
  - command-chain

# cross builds are significantly faster on launchpad
architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [amd64]
    build-for: [arm64]
  - build-on: [amd64]
    build-for: [armhf]

environment:
  # required for proper color display
  COLORTERM: truecolor
  # detects if bugit is run through ssh
  SSH_CONNECTION: $SSH_CONNECTION
  # Specify all the following vars manually if you are using the pipx version
  # remove this to enable debug mode
  PROD: "1"
  # production or qastaging
  APPORT_LAUNCHPAD_INSTANCE: production
  # only used for launchpad
  BUGIT_APP_NAME: bugit-v2
  # change this to the sandbox url for debug mode
  JIRA_SERVER: https://warthogs.atlassian.net
  # let sosreport and oem-getlogs find their libraries
  PYTHONPATH: "$PYTHONPATH:$SNAP/usr/lib/python3/dist-packages"

apps:
  bugit-v2:
    command-chain:
      - env_wrapper.sh
    command: bin/python3 $SNAP/src/bugit_v2/app.py
    completer: src/bugit_v2/bugit-completer.sh

  dump-standard-info:
    # redirect stderr to suppress errors
    command: bin/python3 $SNAP/src/bugit_v2/dump_standard_info.py

  inxi:
    command-chain:
      - env_wrapper.sh
    command: usr/bin/inxi

  oem-getlogs:
    command: usr/bin/oem-getlogs

  sosreport:
    # the patches from the original bugit seem to have been merged
    command: usr/bin/sosreport

parts:
  launcher:
    plugin: dump
    source: snap/local/scripts

  dump-files:
    plugin: dump
    source: src
    organize:
      "*": src/

  bugit-v2:
    plugin: uv
    source: .
    build-snaps:
      - astral-uv
    stage-packages:
      - dmidecode # provides 'dmidecode'
      - pciutils # provides 'lspci'
    after:
      - dump-files

  apport:
    plugin: nil
    stage-packages:
      - apport # provides oem-getlogs, only works on core22

  acpidump:
    plugin: nil
    stage-packages:
      - acpica-tools # provides "acpidump"

  sosreport:
    plugin: nil
    stage-packages:
      - sosreport

  inxi:
    plugin: nil
    stage-packages:
      - inxi
      - mesa-utils # for inxi's graphics report
