#!/bin/sh
#
# This hook allows bugit to run in sudo mode without asking for a password
# NOTE: this hook will cause the installation to fail if --devmode is not
#       specified
# NOTE: this hook is also run ONLY ONCE during install and will not be
#       run again in refreshes/re-installs without --purge 


if ! touch /etc/sudoers.d/bugit-v2; then
    echo "You need to install this app with --devmode"
    echo "Try running 'sudo snap install bugit --devmode'"
    exit 1
fi

set -e
echo "%sudo ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/bugit-v2
# this with the layout key in snapcraft.yaml overrides the snap's /etc/os-release
cp /var/lib/snapd/hostfs/etc/os-release $SNAP_COMMON/etc/os-release